config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :users do
    resources :campaigns do
      resources :campaign_followups do
        resources :email_followups
      end
      resources :contacts do
        collection { post :import }
      end
    end
  end
  root "home#index"

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :campaign



  def self.import(file, campaign_id)
    CSV.foreach(file.path, headers: true) do |row|
      contact_hash = row.to_hash
      if !contact_hash["E-mail Address"].blank? && !contact_hash["Job Title"].blank? && !contact_hash["Company"].blank? #&& !Contact.find_by_email(contact_hash["E-mail Address"])
        unless contact_include?(contact_hash["Company"], contact_hash["Job Title"])
          Contact.create(first_name: contact_hash["First Name"], last_name: contact_hash["Last Name"], email: contact_hash["E-mail Address"], company: contact_hash["Company"], job_title: contact_hash["Job Title"], campaign_id: campaign_id)
        end
      end
    end
   end

   def self.contact_include?(company, job_title)
     filter = ["seo","digital marketing","digital", "marketing","ppc","social media","dbc","developer","blogger","dev bootcamp", "software engineer", "freelance","web design","designer","graphic designer"]
     filter.each do |f|
       if company.downcase.include?(f) || job_title.downcase.include?(f)
         return true
       end
     end
     return false
   end

end

# Contact.all.each do |c|
#   if c.job_title.downcase.include?("seo") ||c.company.downcase.include?("digital maketing")
#     puts c.job_title
#     puts c.company
#   end
# end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  def import
    Contact.import(params[:file], params[:campaign_id])
    redirect_to root_url, notice: "Contacts imported."
  end
  # GET /contacts
  # GET /contacts.json
  def index
    @campaign = Campaign.find params[:campaign_id]
    @contacts = @campaign.contacts
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
    @campaign = Campaign.find params[:campaign_id]
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)
    respond_to do |format|
      if @contact.save
        format.html { redirect_to user_campaign_contacts_path(current_user,params[:campaign_id]), notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to user_campaign_contacts_path(current_user,params[:campaign_id]), notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:first_name, :last_name, :phone_number, :industry, :description, :notes, :email, :company, :job_title, :campaign_id)
    end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.erb
<%= form_for([current_user, @campaign, @contact]) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :phone_number %><br>
    <%= f.text_field :phone_number %>
  </div>
  <div class="field">
    <%= f.label :industry %><br>
    <%= f.text_field :industry %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_field :notes %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :company %><br>
    <%= f.text_field :company %>
  </div>
  <div class="field">
    <%= f.label :job_title %><br>
    <%= f.text_field :job_title %>
  </div>

  <div class="actions">
    <%= hidden_field_tag "contact[campaign_id]", @campaign.id%>
    <%= f.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<div class="col-lg-12">
  <div class="page-header">
    <h1 id="tables">Contacts</h1>
  </div>

  <div class="bs-component">
    <table class="table table-striped table-hover ">
      <thead>
        <tr>
          <th>Full Name</th>
          <th>Email</th>
          <th>Company</th>
          <th>Job title</th>
        </tr>
      </thead>
      <tbody>
        <% @contacts.each do |contact| %>
          <tr>
            <td><%= "#{contact.first_name} #{contact.last_name}" %></td>
            <td><%= contact.email %></td>
            <td><%= contact.company %></td>
            <td><%= contact.job_title %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>


<%= form_tag import_user_campaign_contacts_path(current_user,@campaign.id), multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import" %>
<% end %>
<%= link_to 'Add Contacts', new_user_campaign_contact_path(current_user,@campaign) %>

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= render 'form' %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @contact.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @contact.last_name %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @contact.phone_number %>
</p>

<p>
  <strong>Industry:</strong>
  <%= @contact.industry %>
</p>

<p>
  <strong>Description:</strong>
  <%= @contact.description %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @contact.notes %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<p>
  <strong>Company:</strong>
  <%= @contact.company %>
</p>

<p>
  <strong>Job title:</strong>
  <%= @contact.job_title %>
</p>

<p>
  <strong>Locaiton:</strong>
  <%= @contact.locaiton %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>