config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :users do
    resources :campaigns do
      resources :campaign_followups do
        resources :email_followups
      end
      resources :contacts do
        collection { post :import }
      end
    end
  end
  root "home#index"

end

app/models/campaign.rb
class Campaign < ActiveRecord::Base
  belongs_to :user
  has_many :contacts
  has_many :campaign_followups
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_campaign, only: [:show, :edit, :update, :destroy]
  # GET /campaigns
  # GET /campaigns.json
  def index
    @campaigns = Campaign.all
  end

  # GET /campaigns/1
  # GET /campaigns/1.json
  def show
    @contacts = @campaign.contacts.order(first_name: :asc)
    @campaign_followups = @campaign.campaign_followups
  end

  # GET /campaigns/new
  def new
    @campaign = Campaign.new
  end

  # GET /campaigns/1/edit
  def edit
  end

  # POST /campaigns
  # POST /campaigns.json
  def create
    @campaign = Campaign.new(campaign_params)
    @campaign.user_id = current_user.id
    respond_to do |format|
      if @campaign.save
        format.html { redirect_to user_campaigns_path(current_user), notice: 'Campaign was successfully created.' }
        format.json { render :show, status: :created, location: @campaign }
      else
        format.html { render :new }
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /campaigns/1
  # PATCH/PUT /campaigns/1.json
  def update
    respond_to do |format|
      if @campaign.update(campaign_params)
        format.html { redirect_to @campaign, notice: 'Campaign was successfully updated.' }
        format.json { render :show, status: :ok, location: @campaign }
      else
        format.html { render :edit }
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /campaigns/1
  # DELETE /campaigns/1.json
  def destroy
    @campaign.destroy
    respond_to do |format|
      format.html { redirect_to user_campaigns_path(current_user), notice: 'Campaign was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_campaign
      @campaign = Campaign.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def campaign_params
      params.require(:campaign).permit(:user_id, :name)
    end
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/views/campaigns/_form.html.erb
<%= form_for([current_user, @campaign]) do |f| %>
  <% if @campaign.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@campaign.errors.count, "error") %> prohibited this campaign from being saved:</h2>

      <ul>
      <% @campaign.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/campaigns/edit.html.erb
<h1>Editing Campaign</h1>

<%= render 'form' %>

<%= link_to 'Back', user_campaigns_path(current_user, @campaign) %>

app/views/campaigns/index.html.erb
<p id="notice"><%= notice %></p>


<div class="col-lg-12">
  <div class="page-header">
    <h1 id="tables">Campaigns</h1>
  </div>

  <div class="bs-component">
    <table class="table table-striped table-hover ">
      <thead>
        <tr>
          <th>Campaign</th>
          <th>Past Campaign Followups</th>
          <th>Campaign Contacts</th>
          <th>Date Created</th>
        </tr>
      </thead>

      <tbody>
        <% @campaigns.each do |campaign| %>
          <tr>
            <td><%= link_to campaign.name, user_campaign_path(current_user, campaign) %></td>
            <td><%= link_to 'review', user_campaign_campaign_followups_path(current_user, campaign) %></td>
            <td><%= campaign.contacts.count %></td>
            <td><%= campaign.created_at.strftime("%d/%m/%y") %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <div id="source-button" class="btn btn-primary btn-xs" style="display: none;">&lt; &gt;</div></div><!-- /example -->
</div>
<%= link_to 'New Campaign', new_user_campaign_path(current_user, @campaign) %>

app/views/campaigns/new.html.erb
<h1>New Campaign</h1>

<%= render 'form' %>

<%= link_to 'Back', user_campaigns_path(current_user) %>

app/views/campaigns/show.html.erb
  <div class="row">
    <p id="notice"><%= notice %></p>

    <div class="col-md-12"><h3>Manage Campaign</h3>

      <!-- tabs left -->
      <div class="tabbable tabs-left">
        <ul class="nav nav-tabs">
          <li class="active"><a href="#a" data-toggle="tab">Details</a></li>
          <li><a href="#b" data-toggle="tab">Email List</a></li>
          <li><a href="#c" data-toggle="tab">Follow Ups</a></li>
          <li><a href="#d" data-toggle="tab">Settings</a></li>
        </ul>
        <div class="tab-content">
         <div class="tab-pane active" id="a">
            <div class="container">
               <div class="col-9">
                   <%= @campaign.name %>
               </div><br><br>
             <div class="row">
               <div class="col-md-4">
                 <%= form_tag( user_campaign_campaign_followups_path(current_user, @campaign), method: :post, :html => {:class => "form-horizontal"}) do |f| %>
                 <fieldset>
                   <%= select_tag "email_template", options_for_select([ "Coupon", "Coupon Reminder" ], "Coupon"), class: "form-control", id:"select"%>
                 </fieldset>
               </div>
               <div class="col-md-2">
                 <%= submit_tag "Follow Up", class: "btn btn-success" %>
               </div>
               <% end %>
             </div>
           </div>
         </div>
         <div class="tab-pane" id="b">
           <div class="col-md-5">
             <table class="table table-striped table-hover">
               <thead>
                 <tr>
                   <th>Full Name</th>
                   <th>Email</th>
                   <th>Company</th>
                   <th>Job title</th>
                 </tr>
               </thead>
               <tbody>
                 <% @contacts.each do |contact| %>
                   <tr>
                     <td><%= "#{contact.first_name} #{contact.last_name}" %></td>
                     <td><%= contact.email %></td>
                     <td><%= contact.company %></td>
                     <td><%= contact.job_title %></td>
                   </tr>
                 <% end %>
               </tbody>
             </table>
           </div>
         </div>
         <div class="tab-pane" id="c">
           <div class="col-md-5">
             <table class="table table-striped table-hover ">
               <thead>
                 <tr>
                   <th>Campaign</th>
                   <th>Date Of Follow up</th>
                   <th>Contacts Reached</th>

                 </tr>
               </thead>

               <tbody>
                 <% @campaign_followups.each do |cf| %>
                   <tr>
                     <td><%= @campaign.name %></td>
                     <td><%= cf.created_at.strftime("%d/%m/%Y") %></td>
                     <td><%= cf.email_followups.count %></td>
                   </tr>
                 <% end %>
               </tbody>
             </table>
           </div>
         </div>
         <div class="tab-pane" id="d">
             Update Client List
           <%= form_tag import_user_campaign_contacts_path(current_user,@campaign.id), multipart: true do %>
             <%= file_field_tag :file , class:"btn btn-primary"%><br>
             <%= submit_tag "Import New Clients", class:"btn btn-success" %>
           <% end %>
           <div class="col-9">
             <%= link_to 'Edit Campaign', edit_user_campaign_path(current_user, @campaign) %>
           </div>
         </div>
        </div>
      </div>
      <!-- /tabs -->

    </div>
  </div><!-- /row -->

  <div class="modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Modal title</h4>
      </div>
      <div class="modal-body">
        <p>One fine body…</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>