config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :users do
    resources :campaigns do
      resources :campaign_followups do
        resources :email_followups
      end
      resources :contacts do
        collection { post :import }
      end
    end
  end
  root "home#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mailer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <%= csrf_meta_tags %>


</head>
<body>
  <nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Custom Mailer</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <% if user_signed_in? %>
        <ul class="nav navbar-nav">
          <li class="active">
            <%= link_to "Campaigns" , user_campaigns_path(current_user)%>
          </li>
          <li>
            <%= link_to "Activity", "/"%>
          </li>
        </ul>
      <% end %>





      <% if user_signed_in? %>
        <ul class="nav navbar-nav navbar-right">
          <li>
            <a href="#" style="padding:0;"><%= image_tag(current_user.avatar, size: "45x45") %></a>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= current_user.name %> <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %></li>
              <li class="divider"></li>
              <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
            </ul>
          </li>
        </ul>
      <% else %>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %>
        </li>
        <li class="dropdown">
          <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
        </li>
        </ul>
      <% end %>
    </div>
  </div>
</nav>

<div class="container">
  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>
  <%= yield %>

</div>

</body>
</html>